baseURL = 'https://example.com/'
languageCode = 'en-us'
title = 'My Travel Blog'

[params]
  author = 'Florian R.'
  description = 'Travel adventures around the world'

[taxonomies]
  tag = 'tags'
  category = 'categories'
  trip = 'trips'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1

  [[menu.main]]
    name = 'All Posts'
    url = '/posts/'
    weight = 2

  [[menu.main]]
    name = 'Trips'
    url = '/trips/'
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
